# Generated by Django 6.1.1 on 2026-09-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('grupo_muscular', models.CharField(max_length=100)),
                ('instrucciones', models.TextField(blank=True)),
                ('imagen', models.URLField(blank=True)),
                ('video', models.URLField(blank=True)),
            ],
        ),
    ]
