# Generated by Django 6.1.1 on 2026-09-23 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rutina'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField(default=3)),
                ('repeticiones', models.PositiveIntegerField(default=10)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('descanso', models.PositiveIntegerField(default=60, help_text='Descanso en segundos')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='core.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_rutina', to='core.rutina')),
            ],
        ),
    ]
