# Generated by Django 6.1.1 on 2026-09-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_progreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejerciciorutina',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
