# Generated by Django 6.1.1 on 2026-10-01 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ejerciciorutina_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='progreso',
            name='ejercicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progresos', to='core.ejercicio'),
        ),
    ]
